### ISSUE TITLE
Can't get the admin section to work correctly

### ISSUE THREAD

**Issue by adrhumphreys** [mattyboddy/valet-silverstripe-driver#1]
It appears as though a 502 bad gateway shows up for me, any ideas?

**Comment by mattyboddy** [comment]
This was a bit of a head scratcher for me too. Seems to be an issue with nginx / fastcgi that only manifested in admin.

The fix for me was to specify fastcgi_buffers, and fastcgi_buffer_size in valet.conf.
/usr/local/etc/nginx/valet/valet.conf

`
location ~ \.php$ {
  # added params:
  fastcgi_buffers 16 16k;
  fastcgi_buffer_size 32k;
}
`

Be sure to do a "valet restart" once you've added those parameters.
Hopefully this sorts out your issue.

**Comment by adrhumphreys** [comment]
Awesome that fully fixed it, you should add it to the read me for future users 👍

**Comment by mattyboddy** [comment]
Glad to hear it.
Sure, sounds like a smart think to do :)

**Comment by mattyboddy** [comment]
Updated readme to cover this issue.
